Add tracing to op codes and show register values
FuelLabs/fuel-vm pull request #196
Opened 2022-08-24 13:37 UTC by freesig

Adds tracing to the vm's `instruction` call.
Output looks like:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/7286454/186432707-fa5f34db-a2c3-4e2c-a5c2-4e637c9c78cd.png">

2022-08-25 09:49 UTC, vlopes11 requested changes
Looks good overall. A couple of last dets:

- Add related issue: https://github.com/FuelLabs/fuel-vm/issues/96 (note we are not solving the issue, just incrementally adding steps to that direction)
- Protect the tracing via feature

2022-10-09 23:11 UTC, freesig commented
@vlopes11 I wonder if we can use the tracing [compile time filters](https://docs.rs/tracing/latest/tracing/level_filters/index.html#compile-time-filters) to disable tracing with a feature. Then we don't have to put `#[cfg(feature = "tracing")]` all through the code.

2022-10-10 18:49 UTC, Voxelot approved these changes

2022-11-08 01:32 UTC, Voxelot approved these changes

2022-11-08 02:41 UTC, xgreenx approved these changes

2022-11-08 18:06 UTC, merged