The `wasm_bindgen` support of `fuel-asm` and `fuel-types`
FuelLabs/fuel-vm pull request #499
Opened 2023-07-03 16:49 UTC by xgreenx

2023-07-05 12:43 UTC, Dentosal commented on fuel-types/src/array_types.rs
> +            pub fn zeroed_typescritp() -> $i {
`typescritp` -> `typescript`

2023-07-05 12:51 UTC, Dentosal commented on fuel-types/src/array_types.rs
> +            /// Bytes constructor.
Documentation of the panic condition missing

2023-07-05 12:54 UTC, Dentosal requested changes
Only minor issues, but lets fix those before merging

2023-07-10 16:36 UTC, arboleya commented
@xgreenx How can I build these two locally?

I'd assume it is done via `wasm-pack` _(?)_, but I couldn't find any single-liner to do it with the CI scripts.

2023-07-10 16:58 UTC, xgreenx commented
One time install:
```shell
cargo install wasm-bindgen-cli
``

And to build the rust to WASM and WASM to js/ts:
```shell 
cargo build -p fuel-types --target wasm32-unknown-unknown --features typescript --release
cargo build -p fuel-asm --target wasm32-unknown-unknown --features typescript --release
wasm-bindgen --target nodejs --typescript ./target/wasm32-unknown-unknown/release/fuel_types.wasm --out-dir ./typescript_types
wasm-bindgen --target nodejs --typescript ./target/wasm32-unknown-unknown/release/fuel_asm.wasm --out-dir ./typescript_asm
```

2023-07-11 20:37 UTC, Voxelot submitted a review, later dismissed

2023-07-12 13:42 UTC, Dentosal approved these changes

2023-07-21 18:14 UTC, arboleya submitted a review, later dismissed

2023-07-24 19:03 UTC, arboleya approved these changes

2023-07-24 19:09 UTC, merged